# Generated by Django 5.2.5 on 2025-09-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareasMauri', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Nota',
        ),
    ]
